version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
      prefix-scope: "deps"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
      prefix-scope: "deps"
    allow:
      - dependency-type: "indirect"
      - dependency-type: "direct"
